mylog/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('mylogapp.urls')),
    path("users/", include('users.urls')),
]

mylogapp/urls.py
from django.urls import path
from . import views

app_name = 'mylogapp'
urlpatterns = [
    path("", views.index, name='index'),
    path("topics/", views.topics, name='topics'),
    path("topic/<int:topic_id>/", views.topic, name="topic"),
    path("new_topic/", views.new_topic, name="new_topic"),
    path("new_entry/<int:topic_id>/", views.new_entry, name="new_entry"),
    path("edit_entry/<int:entry_id>/", views.edit_entry, name="edit_entry")
]

users/urls.py
from django.contrib.auth.views import login
from django.urls import path

app_name = "users"

urlpatterns = [
    path("login/", login, {"template_name": "users/login.html"}, name="login")
]

mylogapp/models.py
from django.db import models

# Create your models here.


class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

mylogapp/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["text"]
        labels = {"text": ""}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]
        labels = {"text": ""}
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

mylogapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from mylogapp.models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.urls import reverse
# Create your views here.


def index(request):
    return render(request, "mylogapp/index.html")


def topics(request):
    topic = Topic.objects.order_by("date_added")
    content = {"topics": topic}
    return render(request, "mylogapp/topics.html", content)


def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by("-date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "mylogapp/topic.html", context)


def new_topic(request):
    if request.method != "POST":
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("mylogapp:topics"))

    context = {"form": form}
    return render(request, "mylogapp/new_topic.html", context)


def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != "POST":
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse("mylogapp:topic", args=[topic_id]))
    context = {"topic": topic, "form": form}
    return render(request, "mylogapp/new_entry.html", context)


def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != "POST":
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mylogapp:topic', args=[topic.id]))

    context = {"entry": entry, "topic": topic, "form": form}
    return render(request, "mylogapp/edit_entry.html", context)

users/views.py
from django.shortcuts import render

# Create your views here.

mylogapp/templates/mylogapp/base.html
{% block content %}
<p>
    <a href="{% url 'mylogapp:index' %}">my first app</a>
    <a href="{% url 'mylogapp:topics' %}">my topic page</a>
    {% if user.is_authentiucated %}
        hello,{{ user.username }}
    {% else %}
        <a href="{% url 'users:login' %}"
    {% endif %}
</p>

{% endblock content %}

mylogapp/templates/mylogapp/edit_entry.html
{% extends "mylogapp/base.html" %}

{% block content %}
  <p><a href="{% url 'mylogapp:topic' topic.id %}">{{ topic }}</a></p>

  <p>Edit entry:</p>

  <form action="{% url 'mylogapp:edit_entry' entry.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
  </form>

{% endblock content %}

mylogapp/templates/mylogapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "mylogapp/base.html" %}

{% block content %}
     <p>Learning Log helps you keep track of your learning,
        for any topic you're learning about.</p>
{% endblock content %}
</body>
</html>

mylogapp/templates/mylogapp/new_entry.html
{% extends "mylogapp/base.html" %}
{% block content %}
    <p><a href="{% url 'mylogapp:topic' topic.id %}">{{ topic }}</a> </p>

    <p>Add a new entry:</p>
    <form action="{% url 'mylogapp:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add entry</button>
    </form>
{% endblock content %}

mylogapp/templates/mylogapp/new_topic.html
{% extends "mylogapp/base.html" %}

{% block content %}
    <p>Add a new topic:</p>

    <form action="{% url 'mylogapp:new_topic' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">app topic</button>
    </form>
{% endblock content %}

mylogapp/templates/mylogapp/topic.html
{% extends "mylogapp/base.html" %}

{% block content %}

    <p>Topic:{{ topic }}</p>

    <p>Entryies:</p>
    <ul>
        {% for entry in 'entries' %}
            <li>
                <p>{{ entry.date_added|date:'M d. Y H:i' }}</p>
                <p>{{ entry.text|linebreaks }}</p>
                <p>
                    <a href="{% url 'mylogapp:edit_entry' entry.id %}">edit entry</a>
                </p>
            </li>
            {% empty %}
                <li>
                    There are no entries for this topic yet.
                </li>
        {% endfor %}

    </ul>
    <p>
        <a href="{% url 'mylogapp:new_entry' topic.id %}">add new entry</a>
    </p>

{% endblock content %}

mylogapp/templates/mylogapp/topics.html
{% extends "mylogapp/base.html" %}

{% block content %}
    <p>topics</p>

    <ul>
        {% for topic in topics %}
            <li><a href="{% url 'mylogapp:topic' topic.id %}" >{{ topic }}</a></li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'mylogapp:new_topic' %}">Add a new topic:</a>
{% endblock content %}

users/templates/users/login.html
{% extends "mylogapp/base.html" %}
{% block content %}

    {% if form.errors %}
        <P>Your username and password didn't match. Please try again.</P>
    {% endif %}

    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">login</button>
        <input type="hidden" name="next" value="{% url 'mylog:index' %}">
    </form>
{% endblock content %}